/**
 * NEURION OS — Prebuild: Embed API Key
 * 
 * Este script roda ANTES do build (npm run dist).
 * Ele lê a API key de secrets/openai-key.txt, criptografa com AES-256-CBC,
 * e gera um arquivo electron/_bundled.js que é incluído no app.
 * 
 * O arquivo gerado contém APENAS a key criptografada como constante JS.
 * Nenhum arquivo secrets/ vai para o instalador.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SECRETS_FILE = path.join(__dirname, '..', 'secrets', 'openai-key.txt');
const OUTPUT_FILE = path.join(__dirname, '_bundled.js');

// Derivação de chave baseada em identificadores do app (não é um segredo externo)
const DERIVE_MATERIAL = 'NEURION-OS-v26-EMBED-' + require('../package.json').version;
const DERIVED_KEY = crypto.createHash('sha256').update(DERIVE_MATERIAL).digest();

function encrypt(plaintext) {
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv('aes-256-cbc', DERIVED_KEY, iv);
  let encrypted = cipher.update(plaintext, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return iv.toString('hex') + ':' + encrypted;
}

// --- MAIN ---
console.log('[NEURION Prebuild] Verificando secrets/openai-key.txt ...');

if (!fs.existsSync(SECRETS_FILE)) {
  console.log('[NEURION Prebuild] ⚠ Arquivo secrets/openai-key.txt não encontrado. Build sem key embutida.');
  // Gerar arquivo vazio (sem key)
  fs.writeFileSync(OUTPUT_FILE, `// Auto-generated — no embedded key\nmodule.exports = { EMBEDDED_PAYLOAD: '' };\n`);
  process.exit(0);
}

const rawKey = fs.readFileSync(SECRETS_FILE, 'utf8').trim();

if (!rawKey || rawKey === 'COLE_SUA_API_KEY_AQUI') {
  console.log('[NEURION Prebuild] ⚠ API Key placeholder detectado. Build sem key embutida.');
  fs.writeFileSync(OUTPUT_FILE, `// Auto-generated — no embedded key\nmodule.exports = { EMBEDDED_PAYLOAD: '' };\n`);
  process.exit(0);
}

const encrypted = encrypt(rawKey);

console.log(`[NEURION Prebuild] ✅ API Key criptografada e embutida em electron/_bundled.js`);
console.log(`[NEURION Prebuild]    Tamanho da key: ${rawKey.length} chars → payload: ${encrypted.length} chars`);

fs.writeFileSync(OUTPUT_FILE, 
`// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED by prepare-embed.cjs — DO NOT EDIT MANUALLY
// This file contains an AES-256-CBC encrypted API key.
// It is embedded in the app binary (asar) and NOT visible
// as a standalone file in the installation directory.
// ═══════════════════════════════════════════════════════════════
module.exports = { EMBEDDED_PAYLOAD: '${encrypted}' };
`);

console.log('[NEURION Prebuild] Done.');
